#!/bin/bash

# XCP-ng: in order to retain the FOSS licensing legacy of this code,
# we extracted it from XCP-ng 8.1's xenserver-firstboot package (GPL),
# from file 80-common-criteria.
# The same code also exists in CH 8.2 within the security-tools RPM,
# but that RPM is proprietary so we can't legally take it from there.
# However since this is the same code, we can go with that from the 
# 80-common-criteria file mentioned above.
# So the license of this file, inherited from that, is GPL.

set -e

# Get libcrypto.so full path from CCM
ccm="citrix-crypto-module"
libcrypto=$(rpm -ql ${ccm} | grep "/libcrypto.so" | head -n 1)
if [ "${libcrypto}" == "" ]; then
    echo "Error: could not find ${ccm}"
    exit 1
fi

# Generate pool secret
echo -n $"Creating pool secret using ${libcrypto} (this may take some seconds)"
pool_secret=$(/bin/pool_secret ${libcrypto})
if [ $? -ne 0 ]; then
    echo "Error: failed to generate pool secret"
    exit 1
fi

# Write pool secret to file
token_path="/etc/xensource/ptoken"
touch ${token_path} && chmod 640 ${token_path} && echo -n ${pool_secret} > ${token_path}
echo ' ...done.'

echo "Configured pool secret"

